//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBLServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CBL_Entities : DbContext
    {
        public CBL_Entities()
            : base("name=CBL_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<comment> comments { get; set; }
        public DbSet<forum> forum { get; set; }
        public DbSet<forum_thread> forum_thread { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<group_perm> group_perm { get; set; }
        public DbSet<permission> permissions { get; set; }
        public DbSet<rig> rigs { get; set; }
        public DbSet<thread> threads { get; set; }
        public DbSet<thread_comment> thread_comment { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<user_group> user_group { get; set; }
    }
}
