//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBLServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class forum_thread
    {
        public int forum_thread_id { get; set; }
        public int user_id { get; set; }
        public int forum_id { get; set; }
        public int thread_id { get; set; }
    
        public virtual forum forum { get; set; }
        public virtual user user { get; set; }
        public virtual thread thread { get; set; }
    }
}
