//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBLServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class forum
    {
        public forum()
        {
            this.forum_thread = new HashSet<forum_thread>();
        }
    
        public int forum_id { get; set; }
        public string forum_name { get; set; }
        public string forum_description { get; set; }
        public string forum_permission { get; set; }
        public Nullable<int> forum_islocked { get; set; }
    
        public virtual ICollection<forum_thread> forum_thread { get; set; }
    }
}
