//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBLServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public permission()
        {
            this.group_perm = new HashSet<group_perm>();
        }
    
        public int perm_id { get; set; }
        public string perm_name { get; set; }
    
        public virtual ICollection<group_perm> group_perm { get; set; }
    }
}
