//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBLServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rig
    {
        public int rig_id { get; set; }
        public int user_id { get; set; }
        public string rig_name { get; set; }
        public string rig_processor { get; set; }
        public string rig_ram { get; set; }
        public string rig_motherboard { get; set; }
        public string rig_GPU { get; set; }
        public string rig_PSU { get; set; }
        public string rig_cooler { get; set; }
        public string rig_case { get; set; }
    
        public virtual user user { get; set; }
    }
}
