//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBLServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.forum_thread = new HashSet<forum_thread>();
            this.rigs = new HashSet<rig>();
            this.thread_comment = new HashSet<thread_comment>();
            this.user_group = new HashSet<user_group>();
        }
    
        public int user_id { get; set; }
        public string user_first { get; set; }
        public string user_last { get; set; }
        public string user_username { get; set; }
        public string user_nickname { get; set; }
        public string user_password { get; set; }
        public string user_address { get; set; }
        public Nullable<int> user_rating_useful { get; set; }
        public string user_gender { get; set; }
        public Nullable<System.DateTime> user_registered_date { get; set; }
        public Nullable<System.DateTime> user_birthday { get; set; }
        public string user_email { get; set; }
        public byte[] user_picture { get; set; }
        public Nullable<int> user_age { get; set; }
        public string user_bio { get; set; }
        public string user_mobile { get; set; }
        public Nullable<int> user_rating_helpful { get; set; }
        public Nullable<int> user_rating_like { get; set; }
        public Nullable<int> user_thread_count { get; set; }
    
        public virtual ICollection<forum_thread> forum_thread { get; set; }
        public virtual ICollection<rig> rigs { get; set; }
        public virtual ICollection<thread_comment> thread_comment { get; set; }
        public virtual ICollection<user_group> user_group { get; set; }
    }
}
